import os, base64

def extract_wifi_details():
	"""Function to extract and display WiFi details """
	os.system('cmd /c "color a"')
	witch_craft = 'DQrilojilojilojilojilojilojilojilpPilojilojilojilojilojilpPilpPilazilazilazilazilazilazilazilazilpPilojilojilojilpPilazilazilazilazilazilazilazilpPilazilazilpPiloggDQrilojilojilojilojilpPilpPilpPilpPilazilazilpPilojilojilojilojilojilazilazilazilazilazilazilojilojilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilaziloggDQrilojilojilojilpPilpPilpPilpPilazilazilazilazilazilazilpPilojilojilazilazilazilazilazilazilpPilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilojilpPilpPilpPilazilazilazilazilazilazilazilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilpPilojilpPilojilojilojilojilojilojilojilpPilpPilojilojilojilpPilazilazilazilazilazilazilpPilojilojilojilojilojilojilojilpPilazilazilazilazilpPiloggDQrilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilpPilojilpPilazilazilazilazilazilpPilpPilpPilpPilpPilpPilpPilpPilazilazilazilazilazilazilaziloggDQrilojilojilojilpPilpPilpPilpPilpPilpPilpPilazilazilpPilpPilpPilpPilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilojilpPilpPilpPilazilazilazilazilpPilpPilpPilpPilpPilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilpPilojilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilojilojilpPilpPilpPilpPilpPilpPilpPilpPilojilpPilpPilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPiloggDQrilojilojilojilojilojilpPilpPilpPilpPilpPilpPilpPilojilojilpPilpPilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilojiloggDQrilojilojilojilojilojilpPilpPilpPilpPilpPilojilojilojilojilpPilpPilpPilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilojiloggDQrilojilojilojilojilpPilojilpPilpPilpPilpPilojilojilpPilpPilpPilpPilojilojilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilojiloggDQrilojilojilojilojilpPilpPilojilojilojilpPilpPilpPilpPilpPilpPilpPilojilojilpPilazilazilazilazilazilazilazilazilazilazilazilazilojilpPilazilpPilazilazilpPilojiloggDQrilojilojilojilojilojilpPilojilojilojilpPilpPilpPilpPilpPilpPilpPilpPilojilojilojilojilpPilpPilazilazilazilazilazilazilazilojilpPilazilazilazilazilazilpPilojiloggDQrilojilojilojilojilojilpPilpPilojilpPilojilojilojilpPilpPilpPilojilojilojilojilazilpPilojilpPilpPilazilazilazilpPilpPilojilpPilazilazilazilazilazilazilojilojiloggDQrilojilojilojilojilojilojilpPilojilojilpPilojilojilojilojilojilojilojilpPilazilazilazilpPilpPilazilpPilpPilojilojilpPilazilazilazilazilazilazilazilpPilojilojiloggDQrilojilojilojilojilojilojilojilpPilojilojilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilpPilazilazilazilazilazilazilazilazilazilazilazilojilojilojiloggDQrilojilojilojilojilojilojilojilpPilpPilojilojilpPilpPilpPilpPilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPilojilojilojiloggDQrilojilojilojilojilojilojilojilojilpPilpPilpPilojilojilojilojilojilpPilpPilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilazilpPilojilojilojilojiloggDQrilojilojilojilojilojilojilojilojilojilpPilpPilpPilojilpPilpPilpPilpPilpPilojilojilojilpPilazilazilazilazilazilazilazilazilazilazilazilpPilojilojilojilojilojiloggDQrilojilojilojilojilojilojilojilojilojilojilpPilpPilpPilojilpPilpPilpPilazilpPilojilojilazilazilazilazilazilazilazilazilazilazilazilpPilojilojilojilojilojilojiloggDQrilojilojilojilojilojilojilojilojilojilojilojilpPilpPilojilpPilpPilpPilpPilojilojilojilpPilazilazilazilazilazilazilazilazilazilpPilojilojilojilojilojilojilojiloggDQrilojilojilojilojilojilojilojilojilojilojilojilojilojilojilpPilpPilpPilojilojilojilpPilpPilazilazilazilazilazilazilazilazilojilojilojilojilojilojilojilojilojiloggDQrilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilpPilpPilpPilojilojilpPilpPilazilazilazilazilazilazilpPilojilojilojilojilojilojilojilojilojilojilogNCg=='
	witch_craft = witch_craft.encode('utf-8')
	witch_craft = base64.b64decode(witch_craft)
	witch_craft = witch_craft.decode('utf-8')
	print(f'\n\n\n\n\t\t\t{witch_craft}\n\n')

	exit = False
	while exit == False:
		wifi_details = input("Select a command by entering a number -> '1) Show registered WiFi list' or '2) Show WiFi details' " 
							"\nOr enter '0' to exit: ")

		# Show a list of registered WiFi
		if str(wifi_details) == '1':
			os.system('cmd /c "color e & netsh wlan show profile"')

		# Display Wifi details including password/security key
		elif str(wifi_details) == '2':
			take_input = input('Please enter your WiFi name: ')
			os.system(f'cmd /c "color a & netsh wlan show profile {take_input} key=clear"')

		# Exit if '0'
		elif str(wifi_details) == '0':
			exit = True
		
		else:
			print('Command invalid')
	return

extract_wifi_details()